### ISSUE TITLE
Yarn Install Failed.

### ISSUE THREAD

**Issue by smohantty** [contco/tefi.app#188]
OS: MAC

Error:
yarn install
yarn install v1.22.15
warning ../../package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://npm.pkg.github.com/download/@contco/core-ui/1.1.10/2cec3e3908b0a52b71e357e7f5a7d4073cc2de2d3a557399c6344cbc831b1330: Request failed \"401 Unauthorized\"".

Could you please guide how to resolve this issue.

Thanks for the great Tool :)

**Comment by Hamzaalam** [comment]
I don't think this package is an issue, the package is privately available used and it's many component in the tefi.app

**Comment by Fahad-Mahmood** [comment]
We've created and used few private packages, they should be made public before you can install them.

**Comment by smohantty** [comment]
> We've created and used few private packages, they should be made public before you can install them.

Thanks.. so currently i can't install and run the application in local host right ?

Anyway will wait till the issue get resolved.

**Comment by saadhithere** [comment]
https://github.com/contco/core-ui is now public

**Comment by Fahad-Mahmood** [comment]
All package repo's are public now. 
Packages can be installed by adding a .npmrc file in the project directory with following:
```
@contco:registry=https://npm.pkg.github.com
//npm.pkg.github.com/:_authToken=ADD_YOUR_GITHUB_PAT_HERE

```
